server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-server  # 应用名称
  cloud:
     config:
        server:
          git:
            uri: https://github.com/yesongliang/learngit #配置文件所在仓库
            username: yesongliang
            password: yesl15570351952
            default-label: master 
#            search-paths: config
